#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_NAME="$(basename "$0")"
CAIDO_URL="${CAIDO_URL:-}"
PAT="${CAIDO_PAT:-}"
CA_CERT_PATH=""
CHROME_USER_DATA_DIR="${CAIDO_CHROME_USER_DATA_DIR:-}"
CHROME_PROFILE_DIRECTORY="${CAIDO_CHROME_PROFILE_DIRECTORY:-}"
CHROME_QUIET_MODE="${CAIDO_CHROME_QUIET_MODE:-1}"
CHROME_GPU_MODE="${CAIDO_CHROME_GPU_MODE:-swiftshader}"
CHROME_EXTRA_ARGS="${CAIDO_CHROME_EXTRA_ARGS:-}"
# Use the effective user/home for this process. This script is often invoked via
# `sudo -u <real-user> ...`, where SUDO_USER may still point at root.
REAL_USER="$(id -un)"
REAL_HOME="${HOME:-}"
if [[ -z "${REAL_HOME}" || ! -d "${REAL_HOME}" ]]; then
  REAL_HOME="$(getent passwd "${REAL_USER}" | cut -d: -f6 || true)"
fi
EXPORT_DIR="${REAL_HOME}/.codex/caido"
ENV_OUT="${EXPORT_DIR}/manual-setup.env"
GUIDE_OUT="${EXPORT_DIR}/manual-setup.txt"

log() {
  printf '[%s] %s\n' "$SCRIPT_NAME" "$*"
}

die() {
  printf '[%s] ERROR: %s\n' "$SCRIPT_NAME" "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash scripts/export-caido-manual-setup.sh [options]

Options:
  --pat TOKEN         Caido PAT to export.
  --ca-cert PATH      Path to the downloaded Caido CA certificate.
  --caido-url URL     Caido local API URL. Defaults to saved value or http://localhost:8080.
  --chrome-user-data-dir PATH
                      Existing Chrome user-data-dir to reuse.
  --chrome-profile-directory NAME
                      Existing profile directory inside the user-data-dir.
  --chrome-quiet-mode 0|1
                      Whether the launcher should reduce background-service
                      noise by default. Defaults to 1.
  --chrome-gpu-mode MODE
                      Launcher GPU mode: swiftshader, system, or disabled.
  --chrome-extra-args "..."
                      Extra Chrome args appended by the launcher.
  --export-dir PATH   Directory for manual setup artifacts.
  -h, --help          Show this help text.

Output:
  - manual-setup.env  shell exports for PAT, URL, proxy, and cert path
  - manual-setup.txt  exact manual Chrome and Codex steps
EOF
}

read_saved_value() {
  local field="$1"
  local secrets_path="${REAL_HOME}/.codex/caido/secrets.json"

  [[ -f "${secrets_path}" ]] || return 0

  python3 - "${secrets_path}" "${field}" <<'PY'
import json
import sys
from pathlib import Path

data = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
field = sys.argv[2]
value = ((data.get("caido") or {}).get(field))
if value:
    print(value)
PY
}

detect_default_ca_cert() {
  local candidate
  for candidate in \
    "${REAL_HOME}/Downloads/ca.crt" \
    "${REAL_HOME}/Downloads/caido.crt" \
    "${REAL_HOME}/Downloads/caido-ca.crt"
  do
    if [[ -f "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done
  return 1
}

parse_args() {
  while (($# > 0)); do
    case "$1" in
      --pat)
        [[ $# -ge 2 ]] || die "--pat requires a value"
        PAT="$2"
        shift 2
        ;;
      --ca-cert)
        [[ $# -ge 2 ]] || die "--ca-cert requires a value"
        CA_CERT_PATH="$2"
        shift 2
        ;;
      --caido-url)
        [[ $# -ge 2 ]] || die "--caido-url requires a value"
        CAIDO_URL="$2"
        shift 2
        ;;
      --chrome-user-data-dir)
        [[ $# -ge 2 ]] || die "--chrome-user-data-dir requires a value"
        CHROME_USER_DATA_DIR="$2"
        shift 2
        ;;
      --chrome-profile-directory)
        [[ $# -ge 2 ]] || die "--chrome-profile-directory requires a value"
        CHROME_PROFILE_DIRECTORY="$2"
        shift 2
        ;;
      --chrome-quiet-mode)
        [[ $# -ge 2 ]] || die "--chrome-quiet-mode requires a value"
        CHROME_QUIET_MODE="$2"
        shift 2
        ;;
      --chrome-gpu-mode)
        [[ $# -ge 2 ]] || die "--chrome-gpu-mode requires a value"
        CHROME_GPU_MODE="$2"
        shift 2
        ;;
      --chrome-extra-args)
        [[ $# -ge 2 ]] || die "--chrome-extra-args requires a value"
        CHROME_EXTRA_ARGS="$2"
        shift 2
        ;;
      --export-dir)
        [[ $# -ge 2 ]] || die "--export-dir requires a value"
        EXPORT_DIR="$2"
        ENV_OUT="${EXPORT_DIR}/manual-setup.env"
        GUIDE_OUT="${EXPORT_DIR}/manual-setup.txt"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown argument: $1"
        ;;
    esac
  done
}

resolve_values() {
  if [[ -z "${CAIDO_URL}" ]]; then
    CAIDO_URL="$(read_saved_value url)"
  fi
  if [[ -z "${CAIDO_URL}" ]]; then
    CAIDO_URL="http://localhost:8080"
  fi

  if [[ -z "${PAT}" ]]; then
    PAT="$(read_saved_value pat)"
  fi

  if [[ -z "${CA_CERT_PATH}" ]]; then
    CA_CERT_PATH="$(detect_default_ca_cert || true)"
  fi
}

write_env_file() {
  mkdir -p "${EXPORT_DIR}"

  cat > "${ENV_OUT}" <<EOF
# Generated by ${SCRIPT_NAME}
export CAIDO_URL='${CAIDO_URL}'
export CAIDO_PROXY_SERVER='127.0.0.1:8080'
export CAIDO_PROXY_BYPASS_LIST='<-loopback>'
export CAIDO_PAT='${PAT:-<fill-me>}'
export CAIDO_CERT_PATH='${CA_CERT_PATH:-<path-to-ca.crt>}'
export CAIDO_CHROME_CERT_MANAGER='chrome://certificate-manager/'
export CAIDO_CHROME_USER_DATA_DIR='${CHROME_USER_DATA_DIR}'
export CAIDO_CHROME_PROFILE_DIRECTORY='${CHROME_PROFILE_DIRECTORY}'
export CAIDO_CHROME_QUIET_MODE='${CHROME_QUIET_MODE}'
export CAIDO_CHROME_GPU_MODE='${CHROME_GPU_MODE}'
export CAIDO_CHROME_EXTRA_ARGS='${CHROME_EXTRA_ARGS}'
EOF
}

write_guide_file() {
  cat > "${GUIDE_OUT}" <<EOF
Caido manual setup
==================

Values
------
CAIDO_URL=${CAIDO_URL}
CAIDO_PROXY_SERVER=127.0.0.1:8080
CAIDO_PROXY_BYPASS_LIST=<-loopback>
CAIDO_PAT=${PAT:-<fill-me>}
CAIDO_CERT_PATH=${CA_CERT_PATH:-<path-to-ca.crt>}
CAIDO_CHROME_USER_DATA_DIR=${CHROME_USER_DATA_DIR:-<optional-existing-user-data-dir>}
CAIDO_CHROME_PROFILE_DIRECTORY=${CHROME_PROFILE_DIRECTORY:-<optional-profile-directory>}
CAIDO_CHROME_QUIET_MODE=${CHROME_QUIET_MODE}
CAIDO_CHROME_GPU_MODE=${CHROME_GPU_MODE}
CAIDO_CHROME_EXTRA_ARGS=${CHROME_EXTRA_ARGS:-<optional-extra-launcher-args>}

Chrome HTTPS trust
------------------
1. Open Chrome.
2. Navigate to chrome://certificate-manager/
3. Open "Installed by you".
4. Under Trusted Certificates, click Import.
5. Select: ${CA_CERT_PATH:-<path-to-ca.crt>}

Chrome proxying through Caido
-----------------------------
Use the repo launcher:
  bash scripts/launch-caido-chrome.sh

If CAIDO_CHROME_USER_DATA_DIR / CAIDO_CHROME_PROFILE_DIRECTORY are set in
manual-setup.env, the launcher will reuse that existing Chrome profile.
If they are blank, the launcher falls back to a dedicated Caido-only profile at
${REAL_HOME}/.config/caido-codex-chrome.

Launcher defaults:
- CAIDO_CHROME_QUIET_MODE=1 suppresses most GCM/background-networking noise.
- CAIDO_CHROME_GPU_MODE=swiftshader avoids common VAAPI/WebGL issues on Kali,
  VMs, and GPU-restricted environments.
- Switch CAIDO_CHROME_GPU_MODE to system if you need native GPU/WebGL.
- Switch CAIDO_CHROME_GPU_MODE to disabled if the browser still crashes while
  initializing GPU services.
- If you reuse a noisy profile with many extensions, set:
    CAIDO_CHROME_EXTRA_ARGS=--disable-extensions
  or leave the profile fields blank to use the dedicated Caido profile instead.

Or launch manually (adjust the browser binary name if your Kali package uses
google-chrome-stable instead of google-chrome):
  google-chrome-stable --proxy-server=127.0.0.1:8080 --proxy-bypass-list="<-loopback>"

No proxy extension is required if you use the launcher or start Chrome with
the proxy flags above. Extensions such as Caido Browser Extension or FoxyProxy
are only optional convenience toggles for your normal browser profile.

If you reuse an existing Chrome profile, fully close other Chrome windows using
that same profile before launching it through Caido.

Codex wrapper setup
-------------------
If you want the repo wrapper to use Caido:
  bash plugins/caido/skills/caido-mode/scripts/caido setup ${PAT:-<your-pat>} ${CAIDO_URL}

Verification
------------
  bash plugins/caido/skills/caido-mode/scripts/caido health
  bash plugins/caido/skills/caido-mode/scripts/caido recent --limit 5
EOF
}

main() {
  [[ -n "${REAL_HOME}" ]] || die "Could not resolve home directory for ${REAL_USER}"
  parse_args "$@"
  resolve_values
  write_env_file
  write_guide_file

  log "Wrote ${ENV_OUT}"
  log "Wrote ${GUIDE_OUT}"
}

main "$@"
